#[[module.imports]]
#path = "github.com/willfaught/paige"

[paige]
color = "#0d6efd" # Bootstrap primary color and theme color for Safari and Windows
math = false # Enable math typesetting
style = "" # CSS included at the end of the stylesheet, before style-last.css

[languages.en]
weight = 10

[[languages.en.menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10

[[languages.en.menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 20

[[languages.en.menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
weight = 30

[[languages.en.menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 40

